package br.com.bulktecnologia.modelo.enums;


public enum Perfil{
	
	ITEM_MENU_ACAO,
	ITEM_MENU_CADASTRO_ALUNO,
	ITEM_MENU_CADASTRO_FUNCIONARIO,
	ITEM_MENU_PESQUISA_ALTERACAO,
	ITEM_MENU_MATRICULA,
	ITEM_MENU_ALOCACAO,
	ITEM_MENU_RELATORIO,
	ITEM_MENU_NOTA_E_FALTA,
	
	ITEM_MENU_GERENCIAR_LAYOUT,
	ITEM_MENU_GERENCIAR_SENHA,
	
	ITEM_MENU_CONFIGURACAO,
	ITEM_PAINEL_ADM_EXTERNO,
	
}

